global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'user-service'
    static_configs:
      - targets: ['172.17.0.1:3001']
    metrics_path: /metrics

  - job_name: 'order-service'
    static_configs:
      - targets: ['172.17.0.1:3002']
    metrics_path: /metrics

  - job_name: 'payment-service'
    static_configs:
      - targets: ['172.17.0.1:3003']
    metrics_path: /metrics